//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public long Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Password { get; set; }
        public int IdRol { get; set; }
        public bool Status { get; set; }
        public string Email { get; set; }
        public int IdTypeDocument { get; set; }
        public string NumberDocument { get; set; }
    
        public virtual Rol Rol { get; set; }
        public virtual TypeDocument TypeDocument { get; set; }
    }
}
